* The raven

url (kr): https://namu.wiki/w/The%20Raven

url (en): https://www.poetryfoundation.org/poems-and-poets/poems/detail/48860


Once upon a midnight dreary, while I pondered, weak and weary,

어느 우울한 한밤중, 쇠약하고 지친 내가 생각에 잠겼을 때,


Over many a quaint and curious volume of forgotten lore—

잊혀진 설화를 담은 수많은 진기하고 신비로운 책을 읽으며


While I nodded, nearly napping, suddenly there came a tapping,

내가 졸다가, 거의 깜박 잠들었을 때, 갑자기 두드리는 소리가 들렸다.


As of some one gently rapping, rapping at my chamber door.

마치 누군가 부드럽게 두드리는 듯한, 내 방문을 두드리는 소리가.


"'Tis some visitor," I muttered, "tapping at my chamber door—
Only this and nothing more."

"방문객이로군," 나는 중얼거렸다. "내 방문을 두드리는 것은—

그저 방문객일 뿐, 아무것도 아니다."



Ah, distinctly I remember it was in the bleak December;

아, 똑똑히 생각나는데 그건 고달펐던 12월이었고

And each seperated dying ember wrought its ghost upon the floor.

죽어가는 불씨가 마루 위에 그림자를 던지고 있었다.

Eagerly I wishied the morrow;—vainly I had sought to borrow

From my books surcease of sorrow—sorrow for the lost Lenore—

나는 간절히 내일이 오기를 바랐고—덧없게도 책을 통해 슬픔을—

죽은 레노어에대한 슬픔을— 잊으려 노력했다.

For the rare and radiant maiden whom the angels name Lenore—

Nameless /here/ for evermore.

천사들이 레노어라 이름지은 그 귀하고 빛나는 아가씨를—

이곳에서는 영원히 그 이름없을 아가씨를
